function [xCenterPoints, yCenterPoints] = GetHexGeometry(x_center_circle, y_center_circle,sens_range)
% This function outputs the center points of the circles of the Hexagonal Pattern

d = sens_range*sqrt(3);
dy = sqrt(3/4);
centerPoints = ...
    [0 0;...
     1 0;...
     -1 0;...
     0.5 dy;...
     0.5 -dy;...
     -0.5 dy;...
     -0.5 -dy];
 
 centerPoints = centerPoints*d;
 
 xCenterPoints = centerPoints(:,1)+x_center_circle;
 yCenterPoints = centerPoints(:,2)+y_center_circle;
 
end


